language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
before_install:
  - pip install codecov
  - pip install moto
after_success:
  codecov
# command to run tests
script:
  - nosetests
  - rm -rf tests/__pycache__
  - coverage run --source=notificationhub_sdk -m unittest tests/*
